### ISSUE TITLE
Cannot import name 'PackageStorage' from 'vstools'

### ISSUE THREAD

**Issue by RyougiKukoc** [Jaded-Encoding-Thaumaturgy/vs-source#34]
vstools=3.2.0

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\__init__.py", line 1, in <module>
    from .formats import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\formats\__init__.py", line 2, in <module>
    from .dvd import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\formats\dvd\__init__.py", line 2, in <module>
    from .IsoFile import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\formats\dvd\IsoFile.py", line 12, in <module>
    from .IsoFileCore import IsoFileCore
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\formats\dvd\IsoFileCore.py", line 15, in <module>
    from ...indexers import DVDExtIndexer, DVDSRCIndexer, ExternalIndexer
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\indexers\__init__.py", line 1, in <module>
    from .base import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vssource\indexers\base.py", line 12, in <module>
    from vstools import (
ImportError: cannot import name 'PackageStorage' from 'vstools' (D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\Lib\site-packages\vstools\__init__.py) ```

**Comment by Vodes** [comment]
Needs 3.3.1, probably should've been updated in the requirements
